name: First test workflow

on: 
  push:
  workflow_dispatch:

jobs:
  run_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v4
      - name: Echo node version
        run: |
          node -v
          ls -a
