name: First test workflow

on: 
  push:
  workflow_dispatch:

jobs:
  run_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      #- uses: actions/checkout@v4
      - name: Download files
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Echo node version
        run: |
          node -v
          ls -a
