name: First test workflow

on: workflow_dispatch

jobs:
  run_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Echo node version
        run: node -v
